language: node_js

node_js:
  - 12

os:
  - linux
  - osx

services:
  - xvfb

branches:
  only:
  - master

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
    fi

install:
  - npm install
  - npm run vscode:prepublish

script:
  - npm test

deploy:
  - provider: script
    script: vsce publish -p $VSCE_TOKEN --packagePath *.vsix