language: node_js

node_js:
  - 12

os:
  - linux
  - osx

dist:
  - xenial

services:
  - xvfb

branches:
  only:
  - master

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
    fi
  - npm install -g vsce webpack webpack-cli typescript

install:
  - npm install
  - npm run vscode:prepublish
  # https://github.com/travis-ci/travis-ci/issues/8813
  - rm -f ./node_modules/.bin/which 

script:
  - npm test --silent

deploy:
  - provider: script
    script: vsce package && vsce publish -p $MARKET_KEY
    cleanup: false
    on:
      condition: "$TRAVIS_OS_NAME == osx"