name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '* 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Installs NodeJS
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      # Runs a single command using the runners shell
      - name: Fetch latest rules.
        run: node kb-generator/kb-generator.js
        env:
          CONFORMITY_APIKEY: ${{ secrets.CONFORMITY_APIKEY }}

      # Check if the rules file was generated.
      - name: Check if the rules file was generated.
        run: '[ -f src/kb.json ] && echo "Rules file was generated."'

      # Installs dependencies
      - name: Install Dependencies
        run: |
          npm ci
          npm run vscode:prepublish

      # Bump version.
      - name: Bump Version.
        run: npm --no-git-tag-version sversion patch

      # Publish Extension.
      - name: Vscode release plugin
        uses: JCofman/vscodeaction@master
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
        with:
          args: publish -p $VSCE_TOKEN